### ISSUE TITLE
nonCG, single context reporting

### ISSUE THREAD

**Issue by amvondras** [PeteHaitch/methtuple#102]
I'm using methtuple (v1.6.0) with the `—mt `flag, ex. 

```
$MT --gzip --nfff --mt CG -m 2  ${i}.bam  
$MT --gzip --nfff --mt CHG -m 2  ${i}.bam  
$MT --gzip --nfff --mt CHH -m 2  ${i}.bam  
```

I noticed that `—mt CG` is outputting CG tuples, ex. CS06.h1.CG.2.tsv.gz

```
chr	strand	pos1	pos2	MM	MU	UM	UU
VITVvi_vCabFran04_v1.1.hap1.chr01	+	240	251	1	0	0	0 ***
VITVvi_vCabFran04_v1.1.hap1.chr01	+	251	259	1	0	0	0 ***
VITVvi_vCabFran04_v1.1.hap1.chr01	+	259	278	1	0	0	0
VITVvi_vCabFran04_v1.1.hap1.chr01	+	278	290	1	0	0	0
```

but `—mt CHH` is outputting CHH _and_ CG, ex.  CS06.h1.CG_CHH.2.tsv.gz

```
chr	strand	pos1	pos2	MM	MU	UM	UU
VITVvi_vCabFran04_v1.1.hap1.chr01	+	234	235	0	0	0	1
VITVvi_vCabFran04_v1.1.hap1.chr01	+	235	240	0	0	1	0
VITVvi_vCabFran04_v1.1.hap1.chr01	+	240	251	1	0	0	0 ***
VITVvi_vCabFran04_v1.1.hap1.chr01	+	251	259	1	0	0	0 ***
VITVvi_vCabFran04_v1.1.hap1.chr01	+	259	274	0	1	0	0
VITVvi_vCabFran04_v1.1.hap1.chr01	+	274	276	0	0	0	1
```

Am I making a use or conceptual error? I had thought `—mt CHH` would only output CHH tuples.

**Comment by PeteHaitch** [comment]
> In the meantime, can you post-hoc filter out CG loci from your CG_CHH output files?

I've realised this probably won't give you what you want because the way the tuples are created in `v1.6.0` means that the tuples include those that are comprised of a CG and a CHH, which I think will mean it 'misses' some tuples of the same type.
E.g., `(CHH, CG, CHH)` in the reference will create 2-tuples: `(CHH, CG)` and `(CG, CHH)` but not `(CHH, CHH)`.

**Comment by PeteHaitch** [comment]
> I'm working on a patch that implements this.

This is currently available on https://github.com/PeteHaitch/methtuple/tree/issue-102
I need to do a little more testing and then, once its working, remember how to make it available via PyPI ...

**Comment by PeteHaitch** [comment]
Hi @amvondras,

I've made a new version of **methtuple** (`v1.7.0`) that fixes the issue.
However, in doing so I've (inadvertanly) broken compatibility with Python 2.7.
I'm strongly inclined to just remove any support for Python 2 since it reached end-of-life on 2020-01-01 (https://www.python.org/downloads/) and because I don't have much time to support **methtuple**.
Are you able to use Python3 and install **methtuple** (`v1.7.0`)?

Cheers,
Pete

**Comment by amvondras** [comment]
> new version of **methtuple** (`v1.7.0`)

I will try this using Python3 and report back. Thank you!
